# Generated by Django 2.2.9 on 2020-01-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desc',
            new_name='content',
        ),
    ]
